plugins { id 'com.android.application' }
android {
    namespace 'com.zyvo.masjidemohammadi'
    compileSdk 34
    defaultConfig {
        applicationId 'com.zyvo.masjidemohammadi'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures { viewBinding true }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
